[2025-05-21T09:39:15.707+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:39:09.230246+00:00 [queued]>
[2025-05-21T09:39:15.730+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:39:09.230246+00:00 [queued]>
[2025-05-21T09:39:15.731+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T09:39:15.761+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 09:39:09.230246+00:00
[2025-05-21T09:39:15.768+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2025-05-21T09:39:15.779+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'manual__2025-05-21T09:39:09.230246+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmp5sacsn6y']
[2025-05-21T09:39:15.783+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask process_weather_data
[2025-05-21T09:39:15.820+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:39:15.886+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:39:09.230246+00:00 [running]> on host 00732dad519c
[2025-05-21T09:39:16.003+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:39:09.230246+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T09:39:09.230246+00:00'
[2025-05-21T09:39:16.005+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T09:39:16.006+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T09:39:16.016+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T09:39:16.025+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T09:39:20.277+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T09:39:20.811+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-21T09:39:20.812+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T09:39:20.821+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T09:39:23.010+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T09:39:23.098+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceUtils: ==============================================================
[2025-05-21T09:39:23.100+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T09:39:23.101+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceUtils: ==============================================================
[2025-05-21T09:39:23.102+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T09:39:23.140+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T09:39:23.160+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T09:39:23.161+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T09:39:23.286+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T09:39:23.287+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T09:39:23.296+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T09:39:23.299+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T09:39:23.300+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T09:39:23.981+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO Utils: Successfully started service 'sparkDriver' on port 41431.
[2025-05-21T09:39:24.073+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T09:39:24.164+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T09:39:24.206+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T09:39:24.208+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T09:39:24.216+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T09:39:24.293+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0a55b2c3-3b31-4ae2-9cad-b3af3a1b12a7
[2025-05-21T09:39:24.335+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T09:39:24.387+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T09:39:25.087+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-21T09:39:25.184+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-21T09:39:25.185+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-21T09:39:25.186+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T09:39:25.186+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T09:39:25.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T09:39:25.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T09:39:25.187+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T09:39:25.188+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T09:39:25.188+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T09:39:25.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T09:39:25.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T09:39:25.189+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T09:39:25.190+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T09:39:25.192+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T09:39:25.194+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T09:39:25.195+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T09:39:25.196+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:39:25.196+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T09:39:25.197+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T09:39:25.198+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T09:39:25.198+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:39:25.199+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:39:25.199+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:39:25.402+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T09:39:25.521+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.4:7077 after 68 ms (0 ms spent in bootstraps)
[2025-05-21T09:39:25.749+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521093925-0000
[2025-05-21T09:39:25.762+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41031.
[2025-05-21T09:39:25.763+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO NettyBlockTransferService: Server created on 00732dad519c:41031
[2025-05-21T09:39:25.765+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T09:39:25.782+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 00732dad519c, 41031, None)
[2025-05-21T09:39:25.789+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManagerMasterEndpoint: Registering block manager 00732dad519c:41031 with 434.4 MiB RAM, BlockManagerId(driver, 00732dad519c, 41031, None)
[2025-05-21T09:39:25.795+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 00732dad519c, 41031, None)
[2025-05-21T09:39:25.797+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 00732dad519c, 41031, None)
[2025-05-21T09:39:25.815+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521093925-0000/0 on worker-20250521093802-172.18.0.7-38743 (172.18.0.7:38743) with 2 core(s)
[2025-05-21T09:39:25.838+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521093925-0000/0 on hostPort 172.18.0.7:38743 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T09:39:26.395+0000] {subprocess.py:93} INFO - 25/05/21 09:39:26 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521093925-0000/0 is now RUNNING
[2025-05-21T09:39:26.574+0000] {subprocess.py:93} INFO - 25/05/21 09:39:26 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T09:39:27.080+0000] {subprocess.py:93} INFO - 2025-05-21 09:39:27,080 - INFO - Processing weather data from MinIO
[2025-05-21T09:39:27.089+0000] {subprocess.py:93} INFO - 25/05/21 09:39:27 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T09:39:27.095+0000] {subprocess.py:93} INFO - 25/05/21 09:39:27 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp53nk_hd0/spark-warehouse'.
[2025-05-21T09:39:29.129+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T09:39:29.135+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.140+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:39:29.142+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:39:29.144+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:39:29.148+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:39:29.150+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:39:29.154+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:39:29.156+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:39:29.159+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:39:29.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T09:39:29.163+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T09:39:29.166+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:39:29.181+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:39:29.197+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:39:29.200+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:39:29.201+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:39:29.217+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:39:29.217+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:39:29.228+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:39:29.237+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:39:29.238+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:39:29.239+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:39:29.249+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:39:29.254+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:39:29.254+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:39:29.255+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:39:29.256+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:39:29.256+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:39:29.257+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.257+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:39:29.258+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:39:29.258+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T09:39:29.315+0000] {subprocess.py:93} INFO - 2025-05-21 09:39:29,314 - ERROR - Weather data processing failed: An error occurred while calling o35.json.
[2025-05-21T09:39:29.318+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.320+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:39:29.339+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:39:29.340+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:39:29.340+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:39:29.351+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:39:29.357+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:39:29.371+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:39:29.373+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:39:29.394+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T09:39:29.395+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T09:39:29.395+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T09:39:29.396+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T09:39:29.411+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T09:39:29.412+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:39:29.415+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:39:29.416+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:39:29.417+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:39:29.418+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:39:29.419+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:39:29.419+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:39:29.420+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:39:29.420+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:39:29.421+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:39:29.421+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:39:29.422+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:39:29.422+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:39:29.423+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:39:29.423+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:39:29.424+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:39:29.424+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:39:29.425+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.426+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:39:29.426+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:39:29.427+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T09:39:29.427+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:39:29.428+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO SparkUI: Stopped Spark web UI at http://00732dad519c:4040
[2025-05-21T09:39:29.429+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T09:39:29.429+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T09:39:29.537+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T09:39:29.675+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO MemoryStore: MemoryStore cleared
[2025-05-21T09:39:29.680+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO BlockManager: BlockManager stopped
[2025-05-21T09:39:29.741+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T09:39:29.746+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T09:39:29.880+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T09:39:30.269+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T09:39:30.271+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-379deb4a-a3c4-4381-abaf-83b86bb0cf41
[2025-05-21T09:39:30.280+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-2ca78f9c-4c99-4c5b-8e63-269f316e5884/pyspark-00eddc4f-aed8-4b35-8d0c-7d4e027ad9b7
[2025-05-21T09:39:30.283+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-2ca78f9c-4c99-4c5b-8e63-269f316e5884
[2025-05-21T09:39:30.369+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T09:39:30.435+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T093909, start_date=20250521T093915, end_date=20250521T093930
[2025-05-21T09:39:30.511+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T09:39:30.555+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
