[2025-05-20T20:46:03.363+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-20T20:45:34.409584+00:00 [queued]>
[2025-05-20T20:46:03.395+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-20T20:45:34.409584+00:00 [queued]>
[2025-05-20T20:46:03.396+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-20T20:46:03.469+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-20 20:45:34.409584+00:00
[2025-05-20T20:46:03.509+0000] {standard_task_runner.py:57} INFO - Started process 500 to run task
[2025-05-20T20:46:03.527+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'manual__2025-05-20T20:45:34.409584+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpe8dnndng']
[2025-05-20T20:46:03.547+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask process_weather_data
[2025-05-20T20:46:03.613+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T20:46:03.763+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-20T20:45:34.409584+00:00 [running]> on host 54a986196d48
[2025-05-20T20:46:04.264+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T20:45:34.409584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T20:45:34.409584+00:00'
[2025-05-20T20:46:04.274+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T20:46:04.277+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar         --packages org.apache.hadoop:hadoop-aws:3.3.1         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-20T20:46:04.320+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T20:46:04.375+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-20T20:46:13.517+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-20T20:46:13.819+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-05-20T20:46:13.824+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-05-20T20:46:13.839+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-05-20T20:46:13.841+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-e59470c5-a886-4d0b-b3e7-cab809e7f2c5;1.0
[2025-05-20T20:46:13.842+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-20T20:46:14.418+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.1 in central
[2025-05-20T20:46:14.503+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.901 in central
[2025-05-20T20:46:14.613+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-05-20T20:46:14.672+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 809ms :: artifacts dl 22ms
[2025-05-20T20:46:14.673+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-20T20:46:14.674+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.901 from central in [default]
[2025-05-20T20:46:14.675+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.1 from central in [default]
[2025-05-20T20:46:14.676+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-05-20T20:46:14.677+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-20T20:46:14.677+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-20T20:46:14.678+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-20T20:46:14.686+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-20T20:46:14.696+0000] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2025-05-20T20:46:14.704+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-20T20:46:14.723+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-e59470c5-a886-4d0b-b3e7-cab809e7f2c5
[2025-05-20T20:46:14.724+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-20T20:46:14.728+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/21ms)
[2025-05-20T20:46:16.010+0000] {subprocess.py:93} INFO - 25/05/20 20:46:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-20T20:46:16.995+0000] {subprocess.py:93} INFO - 25/05/20 20:46:16 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-20T20:46:20.968+0000] {subprocess.py:93} INFO - 25/05/20 20:46:20 INFO SparkContext: Running Spark version 3.3.1
[2025-05-20T20:46:21.076+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO ResourceUtils: ==============================================================
[2025-05-20T20:46:21.082+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-20T20:46:21.085+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO ResourceUtils: ==============================================================
[2025-05-20T20:46:21.087+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-20T20:46:21.212+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-20T20:46:21.282+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO ResourceProfile: Limiting resource is cpu
[2025-05-20T20:46:21.285+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-20T20:46:21.575+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO SecurityManager: Changing view acls to: airflow
[2025-05-20T20:46:21.586+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-20T20:46:21.591+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO SecurityManager: Changing view acls groups to:
[2025-05-20T20:46:21.596+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO SecurityManager: Changing modify acls groups to:
[2025-05-20T20:46:21.599+0000] {subprocess.py:93} INFO - 25/05/20 20:46:21 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-20T20:46:22.837+0000] {subprocess.py:93} INFO - 25/05/20 20:46:22 INFO Utils: Successfully started service 'sparkDriver' on port 44103.
[2025-05-20T20:46:23.018+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO SparkEnv: Registering MapOutputTracker
[2025-05-20T20:46:23.196+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-20T20:46:23.271+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-20T20:46:23.272+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-20T20:46:23.293+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-20T20:46:23.427+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-6771db55-8e73-433f-8e7c-d4bd9f0778ea
[2025-05-20T20:46:23.498+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-20T20:46:23.585+0000] {subprocess.py:93} INFO - 25/05/20 20:46:23 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-20T20:46:25.046+0000] {subprocess.py:93} INFO - 25/05/20 20:46:25 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-20T20:46:25.184+0000] {subprocess.py:93} INFO - 25/05/20 20:46:25 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-20T20:46:25.185+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-20T20:46:25.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-20T20:46:25.188+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-20T20:46:25.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-20T20:46:25.190+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-20T20:46:25.191+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-20T20:46:25.192+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-20T20:46:25.193+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-20T20:46:25.196+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-20T20:46:25.197+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-20T20:46:25.200+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-20T20:46:25.201+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-20T20:46:25.202+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-20T20:46:25.203+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-20T20:46:25.205+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-20T20:46:25.206+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-20T20:46:25.207+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-20T20:46:25.208+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-20T20:46:25.210+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-20T20:46:25.212+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-20T20:46:25.213+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-20T20:46:25.214+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T20:46:25.214+0000] {subprocess.py:93} INFO - 25/05/20 20:46:25 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.1.jar at spark://54a986196d48:44103/files/org.apache.hadoop_hadoop-aws-3.3.1.jar with timestamp 1747773980917
[2025-05-20T20:46:25.216+0000] {subprocess.py:93} INFO - 25/05/20 20:46:25 INFO Utils: Copying /home/airflow/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.1.jar to /tmp/spark-e50843d8-d244-4841-9dc5-cc44f1909e64/userFiles-8ed97503-9df7-4004-a3aa-87525185cc1d/org.apache.hadoop_hadoop-aws-3.3.1.jar
[2025-05-20T20:46:25.336+0000] {subprocess.py:93} INFO - 25/05/20 20:46:25 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar at spark://54a986196d48:44103/files/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar with timestamp 1747773980917
[2025-05-20T20:46:25.342+0000] {subprocess.py:93} INFO - 25/05/20 20:46:25 INFO Utils: Copying /home/airflow/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar to /tmp/spark-e50843d8-d244-4841-9dc5-cc44f1909e64/userFiles-8ed97503-9df7-4004-a3aa-87525185cc1d/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar
[2025-05-20T20:46:28.607+0000] {subprocess.py:93} INFO - 25/05/20 20:46:28 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://54a986196d48:44103/files/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1747773980917
[2025-05-20T20:46:28.619+0000] {subprocess.py:93} INFO - 25/05/20 20:46:28 INFO Utils: Copying /home/airflow/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar to /tmp/spark-e50843d8-d244-4841-9dc5-cc44f1909e64/userFiles-8ed97503-9df7-4004-a3aa-87525185cc1d/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2025-05-20T20:46:29.242+0000] {subprocess.py:93} INFO - 25/05/20 20:46:29 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-20T20:46:29.575+0000] {subprocess.py:93} INFO - 25/05/20 20:46:29 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 148 ms (0 ms spent in bootstraps)
[2025-05-20T20:46:30.374+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250520204630-0001
[2025-05-20T20:46:30.378+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250520204630-0001/0 on worker-20250520204256-172.18.0.7-35877 (172.18.0.7:35877) with 2 core(s)
[2025-05-20T20:46:30.382+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO StandaloneSchedulerBackend: Granted executor ID app-20250520204630-0001/0 on hostPort 172.18.0.7:35877 with 2 core(s), 1024.0 MiB RAM
[2025-05-20T20:46:30.416+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34157.
[2025-05-20T20:46:30.417+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO NettyBlockTransferService: Server created on 54a986196d48:34157
[2025-05-20T20:46:30.420+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-20T20:46:30.459+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 54a986196d48, 34157, None)
[2025-05-20T20:46:30.469+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO BlockManagerMasterEndpoint: Registering block manager 54a986196d48:34157 with 434.4 MiB RAM, BlockManagerId(driver, 54a986196d48, 34157, None)
[2025-05-20T20:46:30.480+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 54a986196d48, 34157, None)
[2025-05-20T20:46:30.484+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 54a986196d48, 34157, None)
[2025-05-20T20:46:30.970+0000] {subprocess.py:93} INFO - 25/05/20 20:46:30 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250520204630-0001/0 is now RUNNING
[2025-05-20T20:46:31.773+0000] {subprocess.py:93} INFO - 25/05/20 20:46:31 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-20T20:46:32.873+0000] {subprocess.py:93} INFO - 2025-05-20 20:46:32,855 - INFO - Processing weather data from MinIO
[2025-05-20T20:46:32.887+0000] {subprocess.py:93} INFO - 25/05/20 20:46:32 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-20T20:46:32.893+0000] {subprocess.py:93} INFO - 25/05/20 20:46:32 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpknbi0md7/spark-warehouse'.
[2025-05-20T20:46:38.312+0000] {subprocess.py:93} INFO - 25/05/20 20:46:38 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-05-20T20:46:38.490+0000] {subprocess.py:93} INFO - 25/05/20 20:46:38 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-05-20T20:46:38.499+0000] {subprocess.py:93} INFO - 25/05/20 20:46:38 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-05-20T20:46:45.690+0000] {subprocess.py:93} INFO - 25/05/20 20:46:45 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-20T20:46:45.694+0000] {subprocess.py:93} INFO - java.nio.file.AccessDeniedException: s3a://nyc-taxi-data/weather/*.json: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-20T20:46:45.695+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:206)
[2025-05-20T20:46:45.696+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:170)
[2025-05-20T20:46:45.697+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3351)
[2025-05-20T20:46:45.698+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3185)
[2025-05-20T20:46:45.699+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.isDirectory(S3AFileSystem.java:4277)
[2025-05-20T20:46:45.714+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-05-20T20:46:45.720+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-20T20:46:45.728+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-20T20:46:45.729+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-20T20:46:45.730+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-20T20:46:45.731+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-20T20:46:45.749+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-20T20:46:45.754+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-20T20:46:45.767+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-20T20:46:45.769+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-20T20:46:45.770+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-20T20:46:45.771+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-20T20:46:45.771+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-20T20:46:45.781+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-20T20:46:45.787+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-20T20:46:45.788+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-20T20:46:45.789+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-20T20:46:45.790+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-20T20:46:45.791+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T20:46:45.791+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-20T20:46:45.792+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:216)
[2025-05-20T20:46:45.792+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
[2025-05-20T20:46:45.793+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
[2025-05-20T20:46:45.794+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
[2025-05-20T20:46:45.794+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
[2025-05-20T20:46:45.796+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
[2025-05-20T20:46:45.803+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
[2025-05-20T20:46:45.805+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
[2025-05-20T20:46:45.813+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
[2025-05-20T20:46:45.814+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
[2025-05-20T20:46:45.816+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5227)
[2025-05-20T20:46:45.816+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:6189)
[2025-05-20T20:46:45.820+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:6162)
[2025-05-20T20:46:45.828+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5211)
[2025-05-20T20:46:45.829+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5173)
[2025-05-20T20:46:45.830+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5167)
[2025-05-20T20:46:45.830+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:963)
[2025-05-20T20:46:45.831+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$listObjects$7(S3AFileSystem.java:2116)
[2025-05-20T20:46:45.831+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-05-20T20:46:45.832+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:412)
[2025-05-20T20:46:45.833+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:375)
[2025-05-20T20:46:45.833+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.listObjects(S3AFileSystem.java:2107)
[2025-05-20T20:46:45.834+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3322)
[2025-05-20T20:46:45.834+0000] {subprocess.py:93} INFO - 	... 21 more
[2025-05-20T20:46:45.836+0000] {subprocess.py:93} INFO - Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-20T20:46:45.844+0000] {subprocess.py:93} INFO - 	at com.amazonaws.auth.EnvironmentVariableCredentialsProvider.getCredentials(EnvironmentVariableCredentialsProvider.java:50)
[2025-05-20T20:46:45.845+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:177)
[2025-05-20T20:46:45.845+0000] {subprocess.py:93} INFO - 	... 43 more
[2025-05-20T20:46:48.090+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.7:44700) with ID 0,  ResourceProfileId 0
[2025-05-20T20:46:48.204+0000] {subprocess.py:93} INFO - 2025-05-20 20:46:48,203 - ERROR - Weather data processing failed: An error occurred while calling o36.json.
[2025-05-20T20:46:48.205+0000] {subprocess.py:93} INFO - : java.nio.file.AccessDeniedException: s3a://nyc-taxi-data/weather: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-20T20:46:48.206+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:206)
[2025-05-20T20:46:48.207+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:117)
[2025-05-20T20:46:48.207+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.listStatus(S3AFileSystem.java:2810)
[2025-05-20T20:46:48.223+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Globber.listStatus(Globber.java:128)
[2025-05-20T20:46:48.224+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Globber.doGlob(Globber.java:291)
[2025-05-20T20:46:48.226+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Globber.glob(Globber.java:202)
[2025-05-20T20:46:48.227+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.globStatus(S3AFileSystem.java:4253)
[2025-05-20T20:46:48.228+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.globStatus(S3AFileSystem.java:4233)
[2025-05-20T20:46:48.240+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkHadoopUtil.globPath(SparkHadoopUtil.scala:253)
[2025-05-20T20:46:48.241+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$3(DataSource.scala:765)
[2025-05-20T20:46:48.243+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:372)
[2025-05-20T20:46:48.244+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-05-20T20:46:48.249+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-05-20T20:46:48.261+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-05-20T20:46:48.264+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-05-20T20:46:48.270+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-05-20T20:46:48.278+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-05-20T20:46:48.279+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-05-20T20:46:48.281+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[2025-05-20T20:46:48.281+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[2025-05-20T20:46:48.282+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[2025-05-20T20:46:48.283+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[2025-05-20T20:46:48.283+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[2025-05-20T20:46:48.284+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[2025-05-20T20:46:48.284+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-20T20:46:48.285+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:216)
[2025-05-20T20:46:48.285+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
[2025-05-20T20:46:48.286+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
[2025-05-20T20:46:48.288+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
[2025-05-20T20:46:48.289+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
[2025-05-20T20:46:48.290+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
[2025-05-20T20:46:48.290+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
[2025-05-20T20:46:48.291+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
[2025-05-20T20:46:48.293+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
[2025-05-20T20:46:48.296+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
[2025-05-20T20:46:48.299+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5227)
[2025-05-20T20:46:48.302+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:6189)
[2025-05-20T20:46:48.304+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:6162)
[2025-05-20T20:46:48.308+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5211)
[2025-05-20T20:46:48.312+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5173)
[2025-05-20T20:46:48.315+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5167)
[2025-05-20T20:46:48.326+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:963)
[2025-05-20T20:46:48.341+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$listObjects$7(S3AFileSystem.java:2116)
[2025-05-20T20:46:48.346+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-05-20T20:46:48.350+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:412)
[2025-05-20T20:46:48.364+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:375)
[2025-05-20T20:46:48.365+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.listObjects(S3AFileSystem.java:2107)
[2025-05-20T20:46:48.371+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem$ListingOperationCallbacksImpl.lambda$listObjectsAsync$0(S3AFileSystem.java:1750)
[2025-05-20T20:46:48.373+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.CallableSupplier.get(CallableSupplier.java:62)
[2025-05-20T20:46:48.380+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[2025-05-20T20:46:48.382+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T20:46:48.385+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T20:46:48.386+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T20:46:48.387+0000] {subprocess.py:93} INFO - Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-20T20:46:48.388+0000] {subprocess.py:93} INFO - 	at com.amazonaws.auth.EnvironmentVariableCredentialsProvider.getCredentials(EnvironmentVariableCredentialsProvider.java:50)
[2025-05-20T20:46:48.388+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:177)
[2025-05-20T20:46:48.391+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-05-20T20:46:48.400+0000] {subprocess.py:93} INFO - 
[2025-05-20T20:46:48.404+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO SparkUI: Stopped Spark web UI at http://54a986196d48:4040
[2025-05-20T20:46:48.412+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-20T20:46:48.416+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-20T20:46:48.542+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-20T20:46:48.716+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.7:36439 with 366.3 MiB RAM, BlockManagerId(0, 172.18.0.7, 36439, None)
[2025-05-20T20:46:48.782+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO MemoryStore: MemoryStore cleared
[2025-05-20T20:46:48.793+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO BlockManager: BlockManager stopped
[2025-05-20T20:46:48.862+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-20T20:46:48.880+0000] {subprocess.py:93} INFO - 25/05/20 20:46:48 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-20T20:46:49.089+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO SparkContext: Successfully stopped SparkContext
[2025-05-20T20:46:49.338+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO ShutdownHookManager: Shutdown hook called
[2025-05-20T20:46:49.347+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-e50843d8-d244-4841-9dc5-cc44f1909e64
[2025-05-20T20:46:49.356+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-a3ac0883-e1b8-4dab-ab7e-7e4bfd72d88c
[2025-05-20T20:46:49.371+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-e50843d8-d244-4841-9dc5-cc44f1909e64/pyspark-11b19b12-a947-43c1-82bb-673e5788bf1d
[2025-05-20T20:46:49.382+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-05-20T20:46:49.383+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-05-20T20:46:49.384+0000] {subprocess.py:93} INFO - 25/05/20 20:46:49 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-05-20T20:46:49.533+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-20T20:46:49.661+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250520T204534, start_date=20250520T204603, end_date=20250520T204649
[2025-05-20T20:46:49.732+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-20T20:46:49.788+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
