[2025-05-21T09:34:11.322+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:27:22.833952+00:00 [queued]>
[2025-05-21T09:34:11.334+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:27:22.833952+00:00 [queued]>
[2025-05-21T09:34:11.335+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-21T09:34:11.350+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 09:27:22.833952+00:00
[2025-05-21T09:34:11.355+0000] {standard_task_runner.py:57} INFO - Started process 178 to run task
[2025-05-21T09:34:11.358+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'manual__2025-05-21T09:27:22.833952+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpa8kt12u_']
[2025-05-21T09:34:11.361+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask process_weather_data
[2025-05-21T09:34:11.379+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:34:11.419+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:27:22.833952+00:00 [running]> on host e235d42916dc
[2025-05-21T09:34:11.565+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:27:22.833952+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T09:27:22.833952+00:00'
[2025-05-21T09:34:11.570+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T09:34:11.571+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T09:34:11.580+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T09:34:11.589+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T09:34:14.081+0000] {subprocess.py:93} INFO - 25/05/21 09:34:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T09:34:14.291+0000] {subprocess.py:93} INFO - 25/05/21 09:34:14 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-21T09:34:14.292+0000] {subprocess.py:93} INFO - 25/05/21 09:34:14 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T09:34:14.293+0000] {subprocess.py:93} INFO - 25/05/21 09:34:14 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T09:34:15.421+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T09:34:15.453+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO ResourceUtils: ==============================================================
[2025-05-21T09:34:15.453+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T09:34:15.454+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO ResourceUtils: ==============================================================
[2025-05-21T09:34:15.454+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T09:34:15.475+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T09:34:15.487+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T09:34:15.488+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T09:34:15.545+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T09:34:15.546+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T09:34:15.546+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T09:34:15.547+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T09:34:15.547+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T09:34:15.879+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO Utils: Successfully started service 'sparkDriver' on port 39213.
[2025-05-21T09:34:15.947+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T09:34:15.992+0000] {subprocess.py:93} INFO - 25/05/21 09:34:15 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T09:34:16.021+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T09:34:16.023+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T09:34:16.029+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T09:34:16.066+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c818727d-7883-4ae2-aec2-4b216237e868
[2025-05-21T09:34:16.091+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T09:34:16.117+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T09:34:16.442+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-21T09:34:16.477+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-21T09:34:16.478+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-21T09:34:16.478+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T09:34:16.479+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T09:34:16.479+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T09:34:16.479+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T09:34:16.479+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T09:34:16.480+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T09:34:16.480+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T09:34:16.480+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T09:34:16.481+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T09:34:16.481+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T09:34:16.481+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T09:34:16.482+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T09:34:16.482+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T09:34:16.483+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T09:34:16.483+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:34:16.484+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T09:34:16.484+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T09:34:16.484+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T09:34:16.485+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:34:16.485+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:34:16.485+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:34:16.633+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T09:34:16.709+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 48 ms (0 ms spent in bootstraps)
[2025-05-21T09:34:16.886+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521093416-0000
[2025-05-21T09:34:16.895+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35849.
[2025-05-21T09:34:16.896+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO NettyBlockTransferService: Server created on e235d42916dc:35849
[2025-05-21T09:34:16.898+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T09:34:16.906+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e235d42916dc, 35849, None)
[2025-05-21T09:34:16.910+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO BlockManagerMasterEndpoint: Registering block manager e235d42916dc:35849 with 434.4 MiB RAM, BlockManagerId(driver, e235d42916dc, 35849, None)
[2025-05-21T09:34:16.914+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e235d42916dc, 35849, None)
[2025-05-21T09:34:16.916+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e235d42916dc, 35849, None)
[2025-05-21T09:34:16.919+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521093416-0000/0 on worker-20250521093358-172.18.0.5-36249 (172.18.0.5:36249) with 2 core(s)
[2025-05-21T09:34:16.921+0000] {subprocess.py:93} INFO - 25/05/21 09:34:16 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521093416-0000/0 on hostPort 172.18.0.5:36249 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T09:34:17.107+0000] {subprocess.py:93} INFO - 25/05/21 09:34:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521093416-0000/0 is now RUNNING
[2025-05-21T09:34:17.232+0000] {subprocess.py:93} INFO - 25/05/21 09:34:17 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T09:34:17.433+0000] {subprocess.py:93} INFO - 2025-05-21 09:34:17,433 - INFO - Processing weather data from MinIO
[2025-05-21T09:34:17.440+0000] {subprocess.py:93} INFO - 25/05/21 09:34:17 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T09:34:17.444+0000] {subprocess.py:93} INFO - 25/05/21 09:34:17 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp2a39seyq/spark-warehouse'.
[2025-05-21T09:34:18.676+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T09:34:18.678+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:34:18.679+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:34:18.679+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:34:18.680+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:34:18.680+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:34:18.681+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:34:18.681+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:34:18.682+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:34:18.685+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:34:18.686+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T09:34:18.686+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T09:34:18.687+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:34:18.687+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:34:18.688+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:34:18.688+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:34:18.688+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:34:18.689+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:34:18.689+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:34:18.690+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:34:18.690+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:34:18.691+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:34:18.691+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:34:18.692+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:34:18.692+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:34:18.692+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:34:18.693+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:34:18.694+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:34:18.696+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:34:18.699+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:34:18.700+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:34:18.700+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:34:18.701+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T09:34:18.756+0000] {subprocess.py:93} INFO - 2025-05-21 09:34:18,756 - ERROR - Weather data processing failed: An error occurred while calling o35.json.
[2025-05-21T09:34:18.759+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:34:18.766+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:34:18.767+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:34:18.768+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:34:18.769+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:34:18.770+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:34:18.770+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:34:18.774+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:34:18.777+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:34:18.777+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T09:34:18.778+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T09:34:18.778+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T09:34:18.779+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T09:34:18.779+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T09:34:18.780+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:34:18.781+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:34:18.781+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:34:18.781+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:34:18.782+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:34:18.783+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:34:18.784+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:34:18.785+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:34:18.785+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:34:18.786+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:34:18.786+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:34:18.786+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:34:18.787+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:34:18.787+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:34:18.788+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:34:18.788+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:34:18.789+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:34:18.789+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:34:18.790+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:34:18.790+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:34:18.791+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T09:34:18.791+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:34:18.792+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO SparkUI: Stopped Spark web UI at http://e235d42916dc:4040
[2025-05-21T09:34:18.810+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T09:34:18.821+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T09:34:18.875+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T09:34:18.907+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO MemoryStore: MemoryStore cleared
[2025-05-21T09:34:18.908+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO BlockManager: BlockManager stopped
[2025-05-21T09:34:18.922+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T09:34:18.925+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T09:34:18.941+0000] {subprocess.py:93} INFO - 25/05/21 09:34:18 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T09:34:19.312+0000] {subprocess.py:93} INFO - 25/05/21 09:34:19 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T09:34:19.313+0000] {subprocess.py:93} INFO - 25/05/21 09:34:19 INFO ShutdownHookManager: Deleting directory /tmp/spark-97715089-81d0-4418-a7c6-4df9dfacdf23
[2025-05-21T09:34:19.319+0000] {subprocess.py:93} INFO - 25/05/21 09:34:19 INFO ShutdownHookManager: Deleting directory /tmp/spark-0d71a5bb-5246-4741-9bcf-5b54f61945c2
[2025-05-21T09:34:19.325+0000] {subprocess.py:93} INFO - 25/05/21 09:34:19 INFO ShutdownHookManager: Deleting directory /tmp/spark-0d71a5bb-5246-4741-9bcf-5b54f61945c2/pyspark-8f5fa7dd-e928-4a39-a9a8-6182f961ac74
[2025-05-21T09:34:19.370+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T09:34:19.410+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T092722, start_date=20250521T093411, end_date=20250521T093419
[2025-05-21T09:34:19.467+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T09:34:19.496+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
