[2025-05-21T09:35:15.025+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:35:09.166281+00:00 [queued]>
[2025-05-21T09:35:15.038+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:35:09.166281+00:00 [queued]>
[2025-05-21T09:35:15.038+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T09:35:15.058+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 09:35:09.166281+00:00
[2025-05-21T09:35:15.063+0000] {standard_task_runner.py:57} INFO - Started process 378 to run task
[2025-05-21T09:35:15.067+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'manual__2025-05-21T09:35:09.166281+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmppacbjd3g']
[2025-05-21T09:35:15.070+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask process_weather_data
[2025-05-21T09:35:15.090+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:35:15.139+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:35:09.166281+00:00 [running]> on host e235d42916dc
[2025-05-21T09:35:15.255+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:35:09.166281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T09:35:09.166281+00:00'
[2025-05-21T09:35:15.257+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T09:35:15.259+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T09:35:15.272+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T09:35:15.281+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T09:35:18.217+0000] {subprocess.py:93} INFO - 25/05/21 09:35:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T09:35:18.524+0000] {subprocess.py:93} INFO - 25/05/21 09:35:18 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-21T09:35:18.526+0000] {subprocess.py:93} INFO - 25/05/21 09:35:18 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T09:35:18.526+0000] {subprocess.py:93} INFO - 25/05/21 09:35:18 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T09:35:20.151+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T09:35:20.209+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO ResourceUtils: ==============================================================
[2025-05-21T09:35:20.213+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T09:35:20.214+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO ResourceUtils: ==============================================================
[2025-05-21T09:35:20.215+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T09:35:20.242+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T09:35:20.261+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T09:35:20.263+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T09:35:20.364+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T09:35:20.365+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T09:35:20.370+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T09:35:20.371+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T09:35:20.372+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T09:35:20.987+0000] {subprocess.py:93} INFO - 25/05/21 09:35:20 INFO Utils: Successfully started service 'sparkDriver' on port 40997.
[2025-05-21T09:35:21.054+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T09:35:21.146+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T09:35:21.207+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T09:35:21.208+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T09:35:21.226+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T09:35:21.319+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-4d2122c8-5c23-4ff4-b451-aec8d08ec49a
[2025-05-21T09:35:21.346+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T09:35:21.377+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T09:35:21.748+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-21T09:35:21.847+0000] {subprocess.py:93} INFO - 25/05/21 09:35:21 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-21T09:35:21.849+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-21T09:35:21.851+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T09:35:21.853+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T09:35:21.853+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T09:35:21.854+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T09:35:21.863+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T09:35:21.864+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T09:35:21.864+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T09:35:21.866+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T09:35:21.867+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T09:35:21.872+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T09:35:21.873+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T09:35:21.875+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T09:35:21.876+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T09:35:21.877+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T09:35:21.877+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:35:21.878+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T09:35:21.879+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T09:35:21.879+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T09:35:21.879+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:35:21.880+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:35:21.882+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:35:22.042+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T09:35:22.116+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 46 ms (0 ms spent in bootstraps)
[2025-05-21T09:35:22.276+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521093522-0001
[2025-05-21T09:35:22.278+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521093522-0001/0 on worker-20250521093358-172.18.0.5-36249 (172.18.0.5:36249) with 2 core(s)
[2025-05-21T09:35:22.282+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521093522-0001/0 on hostPort 172.18.0.5:36249 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T09:35:22.300+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45831.
[2025-05-21T09:35:22.301+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO NettyBlockTransferService: Server created on e235d42916dc:45831
[2025-05-21T09:35:22.303+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T09:35:22.322+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e235d42916dc, 45831, None)
[2025-05-21T09:35:22.336+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO BlockManagerMasterEndpoint: Registering block manager e235d42916dc:45831 with 434.4 MiB RAM, BlockManagerId(driver, e235d42916dc, 45831, None)
[2025-05-21T09:35:22.346+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e235d42916dc, 45831, None)
[2025-05-21T09:35:22.348+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e235d42916dc, 45831, None)
[2025-05-21T09:35:22.384+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521093522-0001/0 is now RUNNING
[2025-05-21T09:35:22.851+0000] {subprocess.py:93} INFO - 25/05/21 09:35:22 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T09:35:23.305+0000] {subprocess.py:93} INFO - 2025-05-21 09:35:23,304 - INFO - Processing weather data from MinIO
[2025-05-21T09:35:23.312+0000] {subprocess.py:93} INFO - 25/05/21 09:35:23 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T09:35:23.319+0000] {subprocess.py:93} INFO - 25/05/21 09:35:23 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp3v3dpefg/spark-warehouse'.
[2025-05-21T09:35:25.120+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T09:35:25.124+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:35:25.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:35:25.129+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:35:25.131+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:35:25.132+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:35:25.133+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:35:25.133+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:35:25.134+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:35:25.135+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:35:25.135+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T09:35:25.136+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T09:35:25.140+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:35:25.146+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:35:25.147+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:35:25.152+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:35:25.158+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:35:25.161+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:35:25.165+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:35:25.166+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:35:25.167+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:35:25.170+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:35:25.171+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:35:25.172+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:35:25.186+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:35:25.194+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:35:25.202+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:35:25.203+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:35:25.204+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:35:25.204+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:35:25.205+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:35:25.205+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:35:25.205+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T09:35:25.266+0000] {subprocess.py:93} INFO - 2025-05-21 09:35:25,259 - ERROR - Weather data processing failed: An error occurred while calling o35.json.
[2025-05-21T09:35:25.270+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:35:25.271+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:35:25.272+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:35:25.272+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:35:25.273+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:35:25.274+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:35:25.274+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:35:25.276+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:35:25.277+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:35:25.278+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T09:35:25.278+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T09:35:25.279+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T09:35:25.280+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T09:35:25.288+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T09:35:25.289+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:35:25.290+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:35:25.290+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:35:25.291+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:35:25.291+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:35:25.292+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:35:25.292+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:35:25.293+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:35:25.293+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:35:25.293+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:35:25.294+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:35:25.294+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:35:25.295+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:35:25.295+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:35:25.301+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:35:25.306+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:35:25.307+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:35:25.308+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:35:25.308+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:35:25.309+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:35:25.309+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T09:35:25.310+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:35:25.310+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO SparkUI: Stopped Spark web UI at http://e235d42916dc:4040
[2025-05-21T09:35:25.317+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T09:35:25.324+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T09:35:25.393+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T09:35:25.413+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO MemoryStore: MemoryStore cleared
[2025-05-21T09:35:25.414+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO BlockManager: BlockManager stopped
[2025-05-21T09:35:25.428+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T09:35:25.434+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T09:35:25.456+0000] {subprocess.py:93} INFO - 25/05/21 09:35:25 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T09:35:26.039+0000] {subprocess.py:93} INFO - 25/05/21 09:35:26 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T09:35:26.039+0000] {subprocess.py:93} INFO - 25/05/21 09:35:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-1da3861c-e244-4fd9-9f62-c68df91dc8af
[2025-05-21T09:35:26.044+0000] {subprocess.py:93} INFO - 25/05/21 09:35:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-08c219b7-8431-436e-962d-64b19bebb9ef
[2025-05-21T09:35:26.049+0000] {subprocess.py:93} INFO - 25/05/21 09:35:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-1da3861c-e244-4fd9-9f62-c68df91dc8af/pyspark-79bbe915-047c-4487-94b3-7efea8ba105d
[2025-05-21T09:35:26.099+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T09:35:26.144+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T093509, start_date=20250521T093515, end_date=20250521T093526
[2025-05-21T09:35:26.206+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T09:35:26.233+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
