[2025-05-21T09:39:15.700+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T08:38:43.709714+00:00 [queued]>
[2025-05-21T09:39:15.730+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T08:38:43.709714+00:00 [queued]>
[2025-05-21T09:39:15.731+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T09:39:15.761+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 08:38:43.709714+00:00
[2025-05-21T09:39:15.768+0000] {standard_task_runner.py:57} INFO - Started process 222 to run task
[2025-05-21T09:39:15.773+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'scheduled__2025-05-21T08:38:43.709714+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmp7tfjcmso']
[2025-05-21T09:39:15.778+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask process_weather_data
[2025-05-21T09:39:15.814+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:39:15.879+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T08:38:43.709714+00:00 [running]> on host 00732dad519c
[2025-05-21T09:39:15.992+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T08:38:43.709714+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T08:38:43.709714+00:00'
[2025-05-21T09:39:15.994+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T09:39:15.995+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T09:39:16.007+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T09:39:16.016+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T09:39:20.373+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T09:39:20.796+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-21T09:39:20.798+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T09:39:20.813+0000] {subprocess.py:93} INFO - 25/05/21 09:39:20 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T09:39:22.993+0000] {subprocess.py:93} INFO - 25/05/21 09:39:22 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T09:39:23.094+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceUtils: ==============================================================
[2025-05-21T09:39:23.096+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T09:39:23.098+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceUtils: ==============================================================
[2025-05-21T09:39:23.100+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T09:39:23.141+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T09:39:23.160+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T09:39:23.161+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T09:39:23.254+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T09:39:23.256+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T09:39:23.257+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T09:39:23.264+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T09:39:23.266+0000] {subprocess.py:93} INFO - 25/05/21 09:39:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T09:39:24.053+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO Utils: Successfully started service 'sparkDriver' on port 39271.
[2025-05-21T09:39:24.146+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T09:39:24.223+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T09:39:24.274+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T09:39:24.276+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T09:39:24.293+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T09:39:24.405+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-596ab8eb-f621-4b7b-935d-fad700233e49
[2025-05-21T09:39:24.478+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T09:39:24.563+0000] {subprocess.py:93} INFO - 25/05/21 09:39:24 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T09:39:25.179+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-05-21T09:39:25.206+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-05-21T09:39:25.288+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-21T09:39:25.291+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-21T09:39:25.293+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T09:39:25.294+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T09:39:25.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T09:39:25.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T09:39:25.297+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T09:39:25.299+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T09:39:25.299+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T09:39:25.300+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T09:39:25.302+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T09:39:25.303+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T09:39:25.303+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T09:39:25.304+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T09:39:25.306+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T09:39:25.306+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T09:39:25.306+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:39:25.307+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T09:39:25.307+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T09:39:25.307+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T09:39:25.308+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:39:25.309+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:39:25.310+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:39:25.516+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T09:39:25.601+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.4:7077 after 49 ms (0 ms spent in bootstraps)
[2025-05-21T09:39:25.827+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521093925-0001
[2025-05-21T09:39:25.933+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37493.
[2025-05-21T09:39:25.934+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO NettyBlockTransferService: Server created on 00732dad519c:37493
[2025-05-21T09:39:25.942+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T09:39:25.971+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 00732dad519c, 37493, None)
[2025-05-21T09:39:25.976+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManagerMasterEndpoint: Registering block manager 00732dad519c:37493 with 434.4 MiB RAM, BlockManagerId(driver, 00732dad519c, 37493, None)
[2025-05-21T09:39:25.981+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 00732dad519c, 37493, None)
[2025-05-21T09:39:25.997+0000] {subprocess.py:93} INFO - 25/05/21 09:39:25 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 00732dad519c, 37493, None)
[2025-05-21T09:39:26.892+0000] {subprocess.py:93} INFO - 25/05/21 09:39:26 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T09:39:27.236+0000] {subprocess.py:93} INFO - 2025-05-21 09:39:27,235 - INFO - Processing weather data from MinIO
[2025-05-21T09:39:27.244+0000] {subprocess.py:93} INFO - 25/05/21 09:39:27 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T09:39:27.252+0000] {subprocess.py:93} INFO - 25/05/21 09:39:27 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpp9q6vv54/spark-warehouse'.
[2025-05-21T09:39:29.524+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521093925-0001/0 on worker-20250521093802-172.18.0.7-38743 (172.18.0.7:38743) with 2 core(s)
[2025-05-21T09:39:29.570+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T09:39:29.571+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.572+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:39:29.573+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:39:29.575+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:39:29.603+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:39:29.611+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:39:29.612+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:39:29.613+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:39:29.621+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:39:29.622+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T09:39:29.630+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T09:39:29.630+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:39:29.632+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:39:29.633+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:39:29.633+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:39:29.634+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:39:29.635+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:39:29.636+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:39:29.636+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:39:29.638+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:39:29.639+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:39:29.652+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:39:29.654+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:39:29.656+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:39:29.657+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:39:29.658+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:39:29.658+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:39:29.658+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:39:29.659+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.660+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:39:29.667+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:39:29.670+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T09:39:29.672+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521093925-0001/0 on hostPort 172.18.0.7:38743 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T09:39:29.713+0000] {subprocess.py:93} INFO - 2025-05-21 09:39:29,712 - ERROR - Weather data processing failed: An error occurred while calling o35.json.
[2025-05-21T09:39:29.714+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.715+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T09:39:29.715+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T09:39:29.715+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T09:39:29.716+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T09:39:29.716+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T09:39:29.717+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T09:39:29.717+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T09:39:29.717+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T09:39:29.718+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T09:39:29.722+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T09:39:29.723+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T09:39:29.734+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T09:39:29.737+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T09:39:29.739+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:39:29.740+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:39:29.741+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:39:29.742+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:39:29.743+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:39:29.745+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:39:29.746+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:39:29.747+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:39:29.748+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:39:29.749+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:39:29.752+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:39:29.757+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:39:29.774+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:39:29.776+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:39:29.787+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:39:29.787+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:39:29.788+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:39:29.788+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T09:39:29.789+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T09:39:29.789+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T09:39:29.790+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T09:39:29.790+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:39:29.790+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO SparkUI: Stopped Spark web UI at http://00732dad519c:4041
[2025-05-21T09:39:29.812+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T09:39:29.828+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T09:39:29.925+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521093925-0001/0 is now RUNNING
[2025-05-21T09:39:29.975+0000] {subprocess.py:93} INFO - 25/05/21 09:39:29 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T09:39:30.041+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO MemoryStore: MemoryStore cleared
[2025-05-21T09:39:30.042+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO BlockManager: BlockManager stopped
[2025-05-21T09:39:30.057+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T09:39:30.066+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T09:39:30.093+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T09:39:30.573+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T09:39:30.574+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-c50db8ce-feee-43d8-b033-f88d4c5e5f26
[2025-05-21T09:39:30.595+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-62762ac3-681b-4a4d-baf7-56dc457241f2
[2025-05-21T09:39:30.604+0000] {subprocess.py:93} INFO - 25/05/21 09:39:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-62762ac3-681b-4a4d-baf7-56dc457241f2/pyspark-8d8372ab-6a9d-48df-9ea6-f3eb1123333d
[2025-05-21T09:39:30.719+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T09:39:30.793+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T083843, start_date=20250521T093915, end_date=20250521T093930
[2025-05-21T09:39:30.889+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T09:39:30.923+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
