[2025-05-21T09:24:35.399+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T08:24:28.623770+00:00 [queued]>
[2025-05-21T09:24:35.410+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T08:24:28.623770+00:00 [queued]>
[2025-05-21T09:24:35.411+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T09:24:35.430+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 08:24:28.623770+00:00
[2025-05-21T09:24:35.436+0000] {standard_task_runner.py:57} INFO - Started process 191 to run task
[2025-05-21T09:24:35.440+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'scheduled__2025-05-21T08:24:28.623770+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmp86ylfl4z']
[2025-05-21T09:24:35.445+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask process_weather_data
[2025-05-21T09:24:35.467+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:24:35.522+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T08:24:28.623770+00:00 [running]> on host a0c1f0ba11e5
[2025-05-21T09:24:35.644+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T08:24:28.623770+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T08:24:28.623770+00:00'
[2025-05-21T09:24:35.646+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T09:24:35.647+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar         --packages org.apache.hadoop:hadoop-aws:3.3.1         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T09:24:35.656+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T09:24:35.665+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T09:24:39.480+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-21T09:24:39.732+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-05-21T09:24:39.733+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-05-21T09:24:39.741+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-05-21T09:24:39.750+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-a5d64553-e23a-47fb-87ed-2433e894f784;1.0
[2025-05-21T09:24:39.751+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-21T09:24:41.494+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.1 in central
[2025-05-21T09:24:42.268+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.901 in central
[2025-05-21T09:24:43.651+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-05-21T09:24:43.698+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar ...
[2025-05-21T09:24:44.498+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-aws;3.3.1!hadoop-aws.jar (824ms)
[2025-05-21T09:24:44.517+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar ...
[2025-05-21T09:25:09.229+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] com.amazonaws#aws-java-sdk-bundle;1.11.901!aws-java-sdk-bundle.jar (24727ms)
[2025-05-21T09:25:09.247+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.0.7.Final/wildfly-openssl-1.0.7.Final.jar ...
[2025-05-21T09:25:09.295+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.wildfly.openssl#wildfly-openssl;1.0.7.Final!wildfly-openssl.jar (63ms)
[2025-05-21T09:25:09.296+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 3923ms :: artifacts dl 25624ms
[2025-05-21T09:25:09.297+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-21T09:25:09.297+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.901 from central in [default]
[2025-05-21T09:25:09.297+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.1 from central in [default]
[2025-05-21T09:25:09.298+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-05-21T09:25:09.298+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:25:09.299+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-21T09:25:09.299+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-21T09:25:09.300+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:25:09.300+0000] {subprocess.py:93} INFO - 	|      default     |   3   |   3   |   3   |   0   ||   3   |   3   |
[2025-05-21T09:25:09.301+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:25:09.304+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-a5d64553-e23a-47fb-87ed-2433e894f784
[2025-05-21T09:25:09.304+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-21T09:25:09.594+0000] {subprocess.py:93} INFO - 	3 artifacts copied, 0 already retrieved (189078kB/290ms)
[2025-05-21T09:25:10.202+0000] {subprocess.py:93} INFO - 25/05/21 09:25:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T09:25:10.702+0000] {subprocess.py:93} INFO - 25/05/21 09:25:10 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-21T09:25:12.398+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T09:25:12.427+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO ResourceUtils: ==============================================================
[2025-05-21T09:25:12.428+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T09:25:12.429+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO ResourceUtils: ==============================================================
[2025-05-21T09:25:12.429+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T09:25:12.489+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T09:25:12.511+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T09:25:12.512+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T09:25:12.726+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T09:25:12.728+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T09:25:12.729+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T09:25:12.741+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T09:25:12.743+0000] {subprocess.py:93} INFO - 25/05/21 09:25:12 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T09:25:13.979+0000] {subprocess.py:93} INFO - 25/05/21 09:25:13 INFO Utils: Successfully started service 'sparkDriver' on port 34587.
[2025-05-21T09:25:14.150+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T09:25:14.296+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T09:25:14.388+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T09:25:14.404+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T09:25:14.426+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T09:25:14.574+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-4c0b1dc4-0b06-466f-af1f-f4ec8522c073
[2025-05-21T09:25:14.647+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T09:25:14.725+0000] {subprocess.py:93} INFO - 25/05/21 09:25:14 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T09:25:15.571+0000] {subprocess.py:93} INFO - 25/05/21 09:25:15 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-21T09:25:15.648+0000] {subprocess.py:93} INFO - 25/05/21 09:25:15 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-21T09:25:15.650+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-21T09:25:15.651+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T09:25:15.651+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T09:25:15.652+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T09:25:15.652+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T09:25:15.652+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T09:25:15.653+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T09:25:15.653+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T09:25:15.654+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T09:25:15.654+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T09:25:15.654+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T09:25:15.655+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T09:25:15.655+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T09:25:15.656+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T09:25:15.656+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T09:25:15.657+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:25:15.657+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T09:25:15.658+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T09:25:15.658+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T09:25:15.658+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:25:15.659+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:25:15.659+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:25:15.660+0000] {subprocess.py:93} INFO - 25/05/21 09:25:15 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.1.jar at spark://a0c1f0ba11e5:34587/files/org.apache.hadoop_hadoop-aws-3.3.1.jar with timestamp 1747819512387
[2025-05-21T09:25:15.660+0000] {subprocess.py:93} INFO - 25/05/21 09:25:15 INFO Utils: Copying /home/airflow/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.1.jar to /tmp/spark-a4c32b7a-f7ac-4ac5-bb63-95f1d141293e/userFiles-9b37c065-a188-483c-8cf8-894aeaa80195/org.apache.hadoop_hadoop-aws-3.3.1.jar
[2025-05-21T09:25:15.681+0000] {subprocess.py:93} INFO - 25/05/21 09:25:15 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar at spark://a0c1f0ba11e5:34587/files/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar with timestamp 1747819512387
[2025-05-21T09:25:15.682+0000] {subprocess.py:93} INFO - 25/05/21 09:25:15 INFO Utils: Copying /home/airflow/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar to /tmp/spark-a4c32b7a-f7ac-4ac5-bb63-95f1d141293e/userFiles-9b37c065-a188-483c-8cf8-894aeaa80195/com.amazonaws_aws-java-sdk-bundle-1.11.901.jar
[2025-05-21T09:25:16.207+0000] {subprocess.py:93} INFO - 25/05/21 09:25:16 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://a0c1f0ba11e5:34587/files/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1747819512387
[2025-05-21T09:25:16.209+0000] {subprocess.py:93} INFO - 25/05/21 09:25:16 INFO Utils: Copying /home/airflow/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar to /tmp/spark-a4c32b7a-f7ac-4ac5-bb63-95f1d141293e/userFiles-9b37c065-a188-483c-8cf8-894aeaa80195/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2025-05-21T09:25:16.536+0000] {subprocess.py:93} INFO - 25/05/21 09:25:16 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T09:25:16.667+0000] {subprocess.py:93} INFO - 25/05/21 09:25:16 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 79 ms (0 ms spent in bootstraps)
[2025-05-21T09:25:17.013+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521092516-0000
[2025-05-21T09:25:17.026+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41683.
[2025-05-21T09:25:17.028+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO NettyBlockTransferService: Server created on a0c1f0ba11e5:41683
[2025-05-21T09:25:17.033+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T09:25:17.055+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a0c1f0ba11e5, 41683, None)
[2025-05-21T09:25:17.061+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO BlockManagerMasterEndpoint: Registering block manager a0c1f0ba11e5:41683 with 434.4 MiB RAM, BlockManagerId(driver, a0c1f0ba11e5, 41683, None)
[2025-05-21T09:25:17.067+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a0c1f0ba11e5, 41683, None)
[2025-05-21T09:25:17.073+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a0c1f0ba11e5, 41683, None)
[2025-05-21T09:25:17.094+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521092516-0000/0 on worker-20250521092417-172.18.0.7-38761 (172.18.0.7:38761) with 2 core(s)
[2025-05-21T09:25:17.098+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521092516-0000/0 on hostPort 172.18.0.7:38761 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T09:25:17.444+0000] {subprocess.py:93} INFO - 25/05/21 09:25:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521092516-0000/0 is now RUNNING
[2025-05-21T09:25:18.000+0000] {subprocess.py:93} INFO - 25/05/21 09:25:18 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T09:25:18.928+0000] {subprocess.py:93} INFO - 2025-05-21 09:25:18,927 - INFO - Processing weather data from MinIO
[2025-05-21T09:25:18.945+0000] {subprocess.py:93} INFO - 25/05/21 09:25:18 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T09:25:18.954+0000] {subprocess.py:93} INFO - 25/05/21 09:25:18 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpwfuvdnv2/spark-warehouse'.
[2025-05-21T09:25:22.466+0000] {subprocess.py:93} INFO - 25/05/21 09:25:22 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-05-21T09:25:22.512+0000] {subprocess.py:93} INFO - 25/05/21 09:25:22 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-05-21T09:25:22.514+0000] {subprocess.py:93} INFO - 25/05/21 09:25:22 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-05-21T09:25:24.510+0000] {subprocess.py:93} INFO - 25/05/21 09:25:24 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.7:44406) with ID 0,  ResourceProfileId 0
[2025-05-21T09:25:24.729+0000] {subprocess.py:93} INFO - 25/05/21 09:25:24 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.7:41381 with 366.3 MiB RAM, BlockManagerId(0, 172.18.0.7, 41381, None)
[2025-05-21T09:25:25.948+0000] {subprocess.py:93} INFO - 25/05/21 09:25:25 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T09:25:25.959+0000] {subprocess.py:93} INFO - java.nio.file.AccessDeniedException: s3a://nyc-taxi-data/weather/*.json: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-21T09:25:25.969+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:206)
[2025-05-21T09:25:25.970+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:170)
[2025-05-21T09:25:25.971+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3351)
[2025-05-21T09:25:25.971+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3185)
[2025-05-21T09:25:25.977+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.isDirectory(S3AFileSystem.java:4277)
[2025-05-21T09:25:25.993+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-05-21T09:25:25.995+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T09:25:25.996+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T09:25:25.997+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T09:25:25.997+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T09:25:25.998+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T09:25:25.998+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T09:25:25.999+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T09:25:26.001+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T09:25:26.001+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T09:25:26.002+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T09:25:26.002+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T09:25:26.003+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T09:25:26.004+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T09:25:26.004+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T09:25:26.005+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T09:25:26.005+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T09:25:26.006+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T09:25:26.006+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:25:26.007+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-21T09:25:26.040+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:216)
[2025-05-21T09:25:26.045+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
[2025-05-21T09:25:26.056+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
[2025-05-21T09:25:26.059+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
[2025-05-21T09:25:26.061+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
[2025-05-21T09:25:26.067+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
[2025-05-21T09:25:26.074+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
[2025-05-21T09:25:26.078+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
[2025-05-21T09:25:26.080+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
[2025-05-21T09:25:26.084+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
[2025-05-21T09:25:26.085+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5227)
[2025-05-21T09:25:26.085+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:6189)
[2025-05-21T09:25:26.088+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:6162)
[2025-05-21T09:25:26.088+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5211)
[2025-05-21T09:25:26.090+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5173)
[2025-05-21T09:25:26.091+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5167)
[2025-05-21T09:25:26.092+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:963)
[2025-05-21T09:25:26.092+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$listObjects$7(S3AFileSystem.java:2116)
[2025-05-21T09:25:26.093+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-05-21T09:25:26.093+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:412)
[2025-05-21T09:25:26.094+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:375)
[2025-05-21T09:25:26.094+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.listObjects(S3AFileSystem.java:2107)
[2025-05-21T09:25:26.095+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3322)
[2025-05-21T09:25:26.095+0000] {subprocess.py:93} INFO - 	... 21 more
[2025-05-21T09:25:26.096+0000] {subprocess.py:93} INFO - Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-21T09:25:26.096+0000] {subprocess.py:93} INFO - 	at com.amazonaws.auth.EnvironmentVariableCredentialsProvider.getCredentials(EnvironmentVariableCredentialsProvider.java:50)
[2025-05-21T09:25:26.097+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:177)
[2025-05-21T09:25:26.097+0000] {subprocess.py:93} INFO - 	... 43 more
[2025-05-21T09:25:28.156+0000] {subprocess.py:93} INFO - 2025-05-21 09:25:28,156 - ERROR - Weather data processing failed: An error occurred while calling o36.json.
[2025-05-21T09:25:28.157+0000] {subprocess.py:93} INFO - : java.nio.file.AccessDeniedException: s3a://nyc-taxi-data/weather: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-21T09:25:28.158+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:206)
[2025-05-21T09:25:28.159+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:117)
[2025-05-21T09:25:28.159+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.listStatus(S3AFileSystem.java:2810)
[2025-05-21T09:25:28.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Globber.listStatus(Globber.java:128)
[2025-05-21T09:25:28.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Globber.doGlob(Globber.java:291)
[2025-05-21T09:25:28.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Globber.glob(Globber.java:202)
[2025-05-21T09:25:28.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.globStatus(S3AFileSystem.java:4253)
[2025-05-21T09:25:28.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.globStatus(S3AFileSystem.java:4233)
[2025-05-21T09:25:28.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkHadoopUtil.globPath(SparkHadoopUtil.scala:253)
[2025-05-21T09:25:28.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$3(DataSource.scala:765)
[2025-05-21T09:25:28.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:372)
[2025-05-21T09:25:28.163+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-05-21T09:25:28.163+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-05-21T09:25:28.164+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-05-21T09:25:28.164+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-05-21T09:25:28.165+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-05-21T09:25:28.165+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-05-21T09:25:28.165+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-05-21T09:25:28.166+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[2025-05-21T09:25:28.166+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[2025-05-21T09:25:28.167+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[2025-05-21T09:25:28.168+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[2025-05-21T09:25:28.168+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[2025-05-21T09:25:28.169+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[2025-05-21T09:25:28.169+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-21T09:25:28.170+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:216)
[2025-05-21T09:25:28.170+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
[2025-05-21T09:25:28.171+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
[2025-05-21T09:25:28.171+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
[2025-05-21T09:25:28.172+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
[2025-05-21T09:25:28.172+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
[2025-05-21T09:25:28.173+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
[2025-05-21T09:25:28.173+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
[2025-05-21T09:25:28.174+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
[2025-05-21T09:25:28.174+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
[2025-05-21T09:25:28.175+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5227)
[2025-05-21T09:25:28.175+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:6189)
[2025-05-21T09:25:28.175+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:6162)
[2025-05-21T09:25:28.176+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5211)
[2025-05-21T09:25:28.177+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5173)
[2025-05-21T09:25:28.177+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5167)
[2025-05-21T09:25:28.178+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:963)
[2025-05-21T09:25:28.180+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$listObjects$7(S3AFileSystem.java:2116)
[2025-05-21T09:25:28.183+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-05-21T09:25:28.184+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:412)
[2025-05-21T09:25:28.184+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:375)
[2025-05-21T09:25:28.185+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.listObjects(S3AFileSystem.java:2107)
[2025-05-21T09:25:28.185+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem$ListingOperationCallbacksImpl.lambda$listObjectsAsync$0(S3AFileSystem.java:1750)
[2025-05-21T09:25:28.186+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.CallableSupplier.get(CallableSupplier.java:62)
[2025-05-21T09:25:28.186+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[2025-05-21T09:25:28.187+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-21T09:25:28.188+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-21T09:25:28.188+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T09:25:28.188+0000] {subprocess.py:93} INFO - Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
[2025-05-21T09:25:28.189+0000] {subprocess.py:93} INFO - 	at com.amazonaws.auth.EnvironmentVariableCredentialsProvider.getCredentials(EnvironmentVariableCredentialsProvider.java:50)
[2025-05-21T09:25:28.190+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:177)
[2025-05-21T09:25:28.190+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-05-21T09:25:28.191+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:25:28.191+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO SparkUI: Stopped Spark web UI at http://a0c1f0ba11e5:4040
[2025-05-21T09:25:28.191+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T09:25:28.192+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T09:25:28.244+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T09:25:28.288+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO MemoryStore: MemoryStore cleared
[2025-05-21T09:25:28.289+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO BlockManager: BlockManager stopped
[2025-05-21T09:25:28.307+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T09:25:28.317+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T09:25:28.419+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T09:25:28.726+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T09:25:28.727+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO ShutdownHookManager: Deleting directory /tmp/spark-a4c32b7a-f7ac-4ac5-bb63-95f1d141293e
[2025-05-21T09:25:28.734+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO ShutdownHookManager: Deleting directory /tmp/spark-a4c32b7a-f7ac-4ac5-bb63-95f1d141293e/pyspark-bbe9b181-a31f-4b4d-9519-7a81c1f568b2
[2025-05-21T09:25:28.740+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO ShutdownHookManager: Deleting directory /tmp/spark-7466b915-6ef9-4acb-a047-1ab93e6efe2e
[2025-05-21T09:25:28.748+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-05-21T09:25:28.749+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-05-21T09:25:28.750+0000] {subprocess.py:93} INFO - 25/05/21 09:25:28 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-05-21T09:25:28.808+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T09:25:28.853+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T082428, start_date=20250521T092435, end_date=20250521T092528
[2025-05-21T09:25:28.886+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T09:25:28.913+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
